# Generated by Django 5.2.15 on 2026-06-23 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("total_records", models.IntegerField(default=0)),
                ("valid_records", models.IntegerField(default=0)),
                ("invalid_records", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="ShiftRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raw_day_date", models.CharField(max_length=50)),
                ("raw_start", models.CharField(blank=True, max_length=50)),
                ("raw_end", models.CharField(blank=True, max_length=50)),
                ("raw_hours", models.CharField(max_length=20)),
                ("raw_reason", models.CharField(max_length=100)),
                ("day_date", models.DateField(blank=True, null=True)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("duration_hours", models.FloatField(blank=True, null=True)),
                ("reason", models.CharField(max_length=100)),
                ("category_group", models.CharField(max_length=50)),
                ("is_valid", models.BooleanField(default=True)),
                ("is_duplicate", models.BooleanField(default=False)),
                ("anomalies", models.JSONField(default=list)),
                (
                    "upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="api.dataupload",
                    ),
                ),
            ],
            options={
                "ordering": ["day_date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="DataQualityIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_index", models.IntegerField(default=0)),
                ("issue_type", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=500)),
                ("original_value", models.CharField(blank=True, max_length=200)),
                ("resolved_value", models.CharField(blank=True, max_length=200)),
                ("resolution", models.CharField(max_length=200)),
                (
                    "upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues",
                        to="api.dataupload",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality_issues",
                        to="api.shiftrecord",
                    ),
                ),
            ],
            options={
                "ordering": ["row_index", "issue_type"],
            },
        ),
    ]
